### PR TITLE
fix SharedPartnerData deserialization

### PR DESCRIPTION
**Pull request by ryedpar**
SharedPartnerData isn't deserializing as a string since it's a hash.

I added an empty entry to the listing.json as I'm finding in the "moxi_works" demo company's listings.

I used IDictionary<string, object> as the likely best match for the documentation's data type of "hash" and it's more flexible than a full Hashtable data type.

### CODE REVIEW

**Comment by ahatch1490** [comment]
@ryedpar  I'm talking with the API team but I believe I left this as a string because we really do know what the user could dumps in here.

**Comment by ahatch1490** [comment]
@ryedpar First Thanks for the pull request I appreciate that you took the time to look at this.
After talking with @tres this is kind of a junk drawer and we really have no control over what the user puts in here so  its really up to them to figure out how to serialize and desalinize this field.

**Comment by ahatch1490** [comment]
@ryedpar  Before I close this is actually breaking during de-serialization?

**Comment by ryedpar** [comment]
To confirm the change is necessary, simply run the unit tests with the updated TestData/listings.json (i.e. add the "SharedPartnerData": {} json property )

It will fail to deserialize into a string.

What brought this about was my starting to use the "moxi_works" test company, which includes listings with that value in the response json.

**Comment by ahatch1490** [comment]
Does <string, object> work when de-serializing complex json types? 
for example if I had "sharedPartnerData": {"foo" : 1, "bar": "value":100,"value2: { ... some complex json object}} 
could you add a test to check some cases?

**Comment by ryedpar** [comment]
I'll add a few tests, and given what you've said about what could be in there, I'll likely change it to type dynamic/expando. That, or I'll figure out how to force NewtonSoft to leave it as a string.

**Comment by ahatch1490** [comment]
that would be great! I wonder how Newton.Json de-serializer will handle that.

**Comment by ryedpar** [comment]
While writing the unit test for SharedPartnerData I found that the objects I am concerned with weren't in-sync with the actual data coming back from the web service. I went ahead and fixed all that even though it was a much broader change than I initially meant to do.

If you require, I can reset and make these commits separately with many pull requests, but I thought a single code review would be more efficient.

**Comment by ahatch1490** [comment]
I’ll take a look tonight, thanks for the help!

**Comment by ahatch1490** [comment]
Looks good I'm going to merge this

**Comment by ahatch1490** [comment]
going to get this pushed out to nuget over the weekend.

**Comment by ahatch1490** [comment]
pushed new build to nuget 1.2.13, @ryedpar thanks for the PR!

**Comment by ryedpar** [comment]
Great to hear. Thanks!

**Pull request merged**
